let EXIT_CODE_FAILURE = 1

function Main(_)
	return EXIT_CODE_FAILURE
end
